# Generated by Django 5.2.10 on 2026-01-29 12:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0003_cancel_discovery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clouddnsrecord',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='firewallrule',
            options={'ordering': ['priority', 'name']},
        ),
        migrations.RemoveField(
            model_name='bigtableinstance',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='clouddnszone',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='cloudfunction',
            name='environment_variables',
        ),
        migrations.RemoveField(
            model_name='cloudfunction',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='cloudfunction',
            name='max_instances',
        ),
        migrations.RemoveField(
            model_name='cloudfunction',
            name='min_instances',
        ),
        migrations.RemoveField(
            model_name='cloudfunction',
            name='service_account',
        ),
        migrations.RemoveField(
            model_name='cloudnat',
            name='source_subnetwork_ip_ranges',
        ),
        migrations.RemoveField(
            model_name='cloudrun',
            name='concurrency',
        ),
        migrations.RemoveField(
            model_name='cloudrun',
            name='ingress',
        ),
        migrations.RemoveField(
            model_name='cloudrun',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='cloudrun',
            name='port',
        ),
        migrations.RemoveField(
            model_name='cloudrun',
            name='service_account',
        ),
        migrations.RemoveField(
            model_name='cloudrun',
            name='timeout_seconds',
        ),
        migrations.RemoveField(
            model_name='cloudspannerinstance',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='cloudsqlinstance',
            name='backup_enabled',
        ),
        migrations.RemoveField(
            model_name='cloudsqlinstance',
            name='high_availability',
        ),
        migrations.RemoveField(
            model_name='cloudsqlinstance',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='cloudsqlinstance',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='cloudsqlinstance',
            name='private_ip',
        ),
        migrations.RemoveField(
            model_name='cloudstoragebucket',
            name='public_access_prevention',
        ),
        migrations.RemoveField(
            model_name='cloudstoragebucket',
            name='uniform_bucket_level_access',
        ),
        migrations.RemoveField(
            model_name='gkecluster',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='gkecluster',
            name='private_cluster',
        ),
        migrations.RemoveField(
            model_name='gkecluster',
            name='subnet',
        ),
        migrations.RemoveField(
            model_name='gkenodepool',
            name='autoscaling_enabled',
        ),
        migrations.RemoveField(
            model_name='gkenodepool',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='gkenodepool',
            name='preemptible',
        ),
        migrations.RemoveField(
            model_name='gkenodepool',
            name='spot',
        ),
        migrations.RemoveField(
            model_name='iamrole',
            name='included_permissions',
        ),
        migrations.RemoveField(
            model_name='interconnectattachment',
            name='cloud_router_ip',
        ),
        migrations.RemoveField(
            model_name='interconnectattachment',
            name='customer_router_ip',
        ),
        migrations.RemoveField(
            model_name='interconnectattachment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='interconnectattachment',
            name='encryption',
        ),
        migrations.RemoveField(
            model_name='interconnectattachment',
            name='mtu',
        ),
        migrations.RemoveField(
            model_name='interconnectattachment',
            name='partner_metadata',
        ),
        migrations.RemoveField(
            model_name='loadbalancer',
            name='backend_services',
        ),
        migrations.RemoveField(
            model_name='loadbalancer',
            name='health_check',
        ),
        migrations.RemoveField(
            model_name='memorystoreinstance',
            name='authorized_network',
        ),
        migrations.RemoveField(
            model_name='memorystoreinstance',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='ncchub',
            name='routing_vpcs',
        ),
        migrations.RemoveField(
            model_name='nccspoke',
            name='linked_router_appliance_instances',
        ),
        migrations.RemoveField(
            model_name='persistentdisk',
            name='attached_instances',
        ),
        migrations.RemoveField(
            model_name='persistentdisk',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='persistentdisk',
            name='source_snapshot',
        ),
        migrations.RemoveField(
            model_name='pubsubsubscription',
            name='dead_letter_topic',
        ),
        migrations.RemoveField(
            model_name='pubsubsubscription',
            name='filter_expression',
        ),
        migrations.RemoveField(
            model_name='pubsubsubscription',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='pubsubtopic',
            name='message_retention_duration',
        ),
        migrations.RemoveField(
            model_name='pubsubtopic',
            name='schema_settings',
        ),
        migrations.RemoveField(
            model_name='serviceaccount',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subnet',
            name='secondary_ip_ranges',
        ),
        migrations.RemoveField(
            model_name='vpcnetwork',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vpngateway',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vpntunnel',
            name='peer_gcp_gateway',
        ),
        migrations.AddField(
            model_name='bigtableinstance',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bigtableinstance',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bigtableinstance',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='clouddnsrecord',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clouddnsrecord',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clouddnszone',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clouddnszone',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clouddnszone',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cloudfunction',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cloudfunction',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloudfunction',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cloudnat',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cloudnat',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloudnat',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cloudnat',
            name='source_subnetwork_ip_ranges_to_nat',
            field=models.CharField(default='ALL_SUBNETWORKS_ALL_IP_RANGES', max_length=100),
        ),
        migrations.AddField(
            model_name='cloudrouter',
            name='advertised_groups',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloudrun',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cloudrun',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloudrun',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cloudspannerinstance',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cloudspannerinstance',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloudspannerinstance',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cloudsqlinstance',
            name='ip_addresses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalvpngateway',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='externalvpngateway',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalvpngateway',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='firestoredatabase',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firestoredatabase',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firestoredatabase',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='gkecluster',
            name='subnetwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gcp.subnet'),
        ),
        migrations.AddField(
            model_name='gkenodepool',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gkenodepool',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gkenodepool',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='iambinding',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iambinding',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iamrole',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iamrole',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iamrole',
            name='permissions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instancegroup',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instancegroup',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instancegroup',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='instancetemplate',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instancetemplate',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instancetemplate',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='interconnectattachment',
            name='cloud_router_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interconnectattachment',
            name='customer_router_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interconnectattachment',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interconnectattachment',
            name='edge_availability_domain',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='interconnectattachment',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interconnectattachment',
            name='partner_asn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interconnectattachment',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gcp.vpcnetwork'),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='memorystoreinstance',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memorystoreinstance',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memorystoreinstance',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gcp.vpcnetwork'),
        ),
        migrations.AddField(
            model_name='memorystoreinstance',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ncchub',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ncchub',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncchub',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='nccspoke',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nccspoke',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nccspoke',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='persistentdisk',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persistentdisk',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persistentdisk',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='persistentdisk',
            name='users',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pubsubsubscription',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pubsubsubscription',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pubsubsubscription',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pubsubtopic',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pubsubtopic',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pubsubtopic',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='secretmanagersecret',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secretmanagersecret',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secretmanagersecret',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='self_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='subnet',
            name='gateway_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bigtableinstance',
            name='instance_type',
            field=models.CharField(default='PRODUCTION', max_length=50),
        ),
        migrations.AlterField(
            model_name='bigtableinstance',
            name='storage_type',
            field=models.CharField(default='SSD', max_length=50),
        ),
        migrations.AlterField(
            model_name='clouddnsrecord',
            name='record_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clouddnsrecord',
            name='rrdatas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clouddnszone',
            name='visibility',
            field=models.CharField(default='public', max_length=50),
        ),
        migrations.AlterField(
            model_name='cloudfunction',
            name='trigger_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='cloudnat',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nats', to='gcp.cloudrouter'),
        ),
        migrations.AlterField(
            model_name='cloudrouter',
            name='advertise_mode',
            field=models.CharField(default='DEFAULT', max_length=50),
        ),
        migrations.AlterField(
            model_name='cloudrun',
            name='cpu',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='cloudrun',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='cloudrun',
            name='max_instances',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='cloudrun',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='cloudspannerinstance',
            name='config',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cloudspannerinstance',
            name='processing_units',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='cloudsqlinstance',
            name='database_type',
            field=models.CharField(default='MYSQL', max_length=50),
        ),
        migrations.AlterField(
            model_name='cloudsqlinstance',
            name='storage_type',
            field=models.CharField(default='SSD', max_length=20),
        ),
        migrations.AlterField(
            model_name='cloudstoragebucket',
            name='storage_class',
            field=models.CharField(default='STANDARD', max_length=50),
        ),
        migrations.AlterField(
            model_name='externalvpngateway',
            name='redundancy_type',
            field=models.CharField(default='SINGLE_IP_INTERNALLY_REDUNDANT', max_length=50),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='action',
            field=models.CharField(default='allow', max_length=20),
        ),
        migrations.AlterField(
            model_name='gcporganization',
            name='organization_id',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='gcporganization',
            name='service_account_json',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gcpproject',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='gcp.gcporganization'),
        ),
        migrations.AlterField(
            model_name='gkecluster',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gcp.vpcnetwork'),
        ),
        migrations.AlterField(
            model_name='gkenodepool',
            name='disk_type',
            field=models.CharField(default='pd-standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='gkenodepool',
            name='max_node_count',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='gkenodepool',
            name='min_node_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='iamrole',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='iamrole',
            name='stage',
            field=models.CharField(default='GA', max_length=50),
        ),
        migrations.AlterField(
            model_name='instancegroup',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gcp.instancetemplate'),
        ),
        migrations.AlterField(
            model_name='interconnectattachment',
            name='bandwidth',
            field=models.CharField(default='BPS_1G', max_length=50),
        ),
        migrations.AlterField(
            model_name='loadbalancer',
            name='lb_type',
            field=models.CharField(default='HTTP', max_length=50),
        ),
        migrations.AlterField(
            model_name='loadbalancer',
            name='port',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='loadbalancer',
            name='scheme',
            field=models.CharField(default='EXTERNAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='memorystoreinstance',
            name='redis_version',
            field=models.CharField(default='REDIS_6_X', max_length=50),
        ),
        migrations.AlterField(
            model_name='memorystoreinstance',
            name='tier',
            field=models.CharField(default='BASIC', max_length=50),
        ),
        migrations.AlterField(
            model_name='nccspoke',
            name='spoke_type',
            field=models.CharField(default='VPC_NETWORK', max_length=50),
        ),
        migrations.AlterField(
            model_name='persistentdisk',
            name='disk_type',
            field=models.CharField(default='pd-standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='pubsubsubscription',
            name='push_endpoint',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='secretmanagersecret',
            name='replication_type',
            field=models.CharField(default='AUTOMATIC', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vpcnetwork',
            name='routing_mode',
            field=models.CharField(default='REGIONAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='vpntunnel',
            name='detailed_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vpntunnel',
            name='peer_external_gateway_interface',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='iambinding',
            unique_together={('project', 'role', 'member')},
        ),
    ]
