# Generated by Django 5.2.10 on 2026-02-01 12:17

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('gcp', '0006_force_asn_bigint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('connection_preference', models.CharField(default='ACCEPT_AUTOMATIC', max_length=50)),
                ('nat_subnets', models.JSONField(blank=True, null=True)),
                ('target_service', models.CharField(blank=True, max_length=500)),
                ('self_link', models.URLField(blank=True, max_length=500)),
                ('discovered', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_attachments', to='gcp.gcpproject')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Service Attachment',
                'verbose_name_plural': 'Service Attachments',
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceConnectEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('target_service_attachment', models.CharField(blank=True, max_length=500)),
                ('self_link', models.URLField(blank=True, max_length=500)),
                ('discovered', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gcp.vpcnetwork')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psc_endpoints', to='gcp.gcpproject')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'PSC Endpoint',
                'verbose_name_plural': 'PSC Endpoints',
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]